### PR TITLE
Removed default HSE_VALUE

### PR DESCRIPTION
**Pull request by antevir**
This should instead be set using yotta config.

### CODE REVIEW

**Comment by ciarmcom** [comment]
Automatic CI verification build not done, please verify manually.

**Comment by 0xc0170** [comment]
Shall we document this change (readme?), as this file comes from ST package. Once updated ,this changeset might be overlooked, or any other we do.

**Comment by antevir** [comment]
The patch in this repo is only for removing the warning below that is generated from cmsis-core-stm32f429xi:
``` 
#warning HSE_VALUE ignored, using yotta_config values instead
   ^
  In file included from C:/git/hallon/yotta_modules/cmsis-core-stm32f4/cmsis-core-stm32f4/stm32f4xx.h:142:0,
                   from C:/git/hallon/yotta_modules/mbed-hal-st-stm32cubef4/mbed-hal-st-stm32cubef4/stm32f4xx_hal_def.h:48,
                   from C:/git/hallon/yotta_modules/mbed-hal-st-stm32cubef4/mbed-hal-st-stm32cubef4/stm32f4xx_hal_rcc.h:47,
                   from C:/git/hallon/yotta_modules/mbed-hal-st-stm32f429zi/mbed-hal-st-stm32f429zi/stm32f4xx_hal_conf.h:233,
                   from C:/git/hallon/yotta_modules/mbed-hal-st-stm32cubef4/mbed-hal-st-stm32cubef4/stm32f4xx_hal.h:48,
                   from C:/git/hallon/yotta_modules/mbed-hal-st-stm32cubef4/source/stm32f4xx_hal_cec.c:80:
C:/git/hallon/yotta_modules/cmsis-core-stm32f429xi/cmsis-core-stm32f429xi/stm32f429xx.h:68:2: warning: #warning HSE_VALUE ignored, using yotta_config values instead [-Wcpp]
```
The HSE_VALUE will still get the right value with https://github.com/ARMmbed/cmsis-core-stm32f429xi/pull/12

If the files in this repo rather should be left untouched we can probably make a slightly different fix in cmsis-core-stm32f429xi instead.

**Comment by antevir** [comment]
How about moving the YOTTA_CFG_HARDWARE_EXTERNALCLOCK stuff to cmsis-core-stm32f4/cmsis.h instead, In this way the ST files does not need to be modified at all for supporting yotta config of HSE_VALUE, plus then all other STM32F4xx will get the same yotta config support.

**Comment by antevir** [comment]
Just saw that cmsis-core-stm32f4/cmsis.h is currently not force includeded, so this might not be a good idea.

**Comment by antevir** [comment]
I have updated ARMmbed/cmsis-core-stm32f429xi#12 so the patch in this repo is not needed

**Comment by 0xc0170** [comment]
The updated PR - will generate warning, wont it?

**Comment by antevir** [comment]
It will only generate a warning if the user sets the HSE_VALUE manually from makefile etc, it will not generate the warning above originating from the default HSE_VALUE set in cmsis-core-stm32f4/stm32f4xx.h.
Since I moved the HSE_VALUE check back to the c-file, it will only be checked when this file is compiled. And since system_stm32f4xx.c does not include stm32f4xx_hal_conf.h, the HSE_VALUE will not be set.

**Comment by antevir** [comment]
Closed this PR since it is not needed https://github.com/ARMmbed/cmsis-core-stm32f429xi/pull/12 any more

**Pull request closed without merging**
