### PR TITLE
Enable AsyncSerial.

### PR DESCRIPTION
**Pull request by niklas-arm**
Refactor `serial_s` object struct.
Add required defines.

Depends on https://github.com/ARMmbed/mbed-hal-st-stm32f4/pull/23.

@bremoran @0xc0170 @bogdanm

### CODE REVIEW

**Comment by 0xc0170** [comment]
LGTM

**Comment by 0xc0170** [comment]
One question, shouldn't object header file be in the stm32f4 module ? It's the same for all those target dependencies like this one.

**Comment by niklas-arm** [comment]
Yes, the object header should be in the stm32f4 module.

**Comment by 0xc0170** [comment]
Can you update your pull requests? I would like to merge Serial async PRs

**Comment by niklas-arm** [comment]
Moving the object header file is not a simple operation, it requires synchronization of *all* repositoties that depend on the stm32f4-hal.
I wasn't planning on doing this right now.

**Comment by bremoran** [comment]
It should be possible to do this in a non-breaking way. First, duplicate the header, rather than moving it. Then, update each dependent module to remove the header and depend on the new version of stm32f4-hal.

While it does require synchronization, nothing will break so long as the contents of all the copies of the header are the same.

**Comment by niklas-arm** [comment]
I agree, I will do this now in a non-breaking way.

**Comment by 0xc0170** [comment]
:+1:

**Comment by niklas-arm** [comment]
After rebase it not depends on ARMmbed/mbed-hal-st-stm32f4#23.

**Pull request merged**
